source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'DistanceGetter_Example' do
  pod "DistanceGetter", :path => "../"
end

target 'DistanceGetter_Tests' do
  pod "DistanceGetter", :path => "../"
end
