source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DistanceGetter_Example', :exclusive => true do
  pod "DistanceGetter", :path => "../"
end

target 'DistanceGetter_Tests', :exclusive => true do
  pod "DistanceGetter", :path => "../"

  
end
